# Generated by Django 2.1.15 on 2020-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20200504_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(default=1, help_text='Between 1 and 10'),
        ),
    ]
